Leitura de CSV com vírgulas no valor das colunas
platiagro/pipelines pull request #104
Opened 2020-11-25 14:25 UTC by AlendeGeraldo

2020-11-25 17:41 UTC, fberanizo requested changes

2020-11-25 17:41 UTC, fberanizo commented on pipelines/controllers/deployments.py
> +    loads_json['data']['names'] = df['columns']
Olá! Essa linha não é correta. `names` deve ser o mesmo que foi retornado pelo seldon. E o retorno do seldon nem sempre é igual às colunas do dataframe.
Por exemplo, no seldon eu posso remover umas colunas do dataframe e com essa linha você está adicionando as colunas de volta.

2020-11-25 17:41 UTC, fberanizo commented on pipelines/controllers/deployments.py
> +    response = requests.post(f"http://istio-ingressgateway:31380/seldon{url}", json=request)
Este método precisa ler outros tipos de arquivo também.
Teste com uma imagem, por favor.
Neste caso o `pd.read_csv` vai lançar exceção.
Mesmo assim, a requisição do seldon deve acontecer, só que com outro formato:
```
request = {
    "binData": "conteúdo da imagem em base64..."
}

Leia o conteúdo do file.
Use esta função para transformar o arquivo em base64:
https://docs.python.org/3/library/base64.html#base64.b64encode

2020-11-25 17:41 UTC, fberanizo commented on pipelines/api/deployments.py
> +@bp.route("seldon/test", methods=["POST"])
@AlendeGeraldo não se esqueça do docstring igual as outras funções deste arquivo...

2020-11-26 16:45 UTC, AlendeGeraldo commented on pipelines/controllers/deployments.py
> +    loads_json['data']['names'] = df['columns']
Subscrevei a coluna para ficar mas legível, só não sabia que havia essa flexibilidade.

2020-12-16 12:19 UTC, closed without merging