Change api /traininings to experiments/../runs and /deployments to /d…
platiagro/pipelines pull request #98
Opened 2020-11-16 15:38 UTC by shiguemi32

…eploymens/.../runs

2020-11-17 12:18 UTC, fberanizo requested changes

2020-11-17 12:18 UTC, fberanizo commented on pipelines/api/experiments.py
> +    return jsonify(logs)
@shiguemi32 esse arquivo pode ser o `api/experiment_runs.py` (depois a gente cria o `api/experiment.py` com as coisas que estão no repo projects).

2020-11-17 12:18 UTC, fberanizo commented on pipelines/api/runs.py
>  from pipelines.controllers.runs import create_run
@shiguemi32 aí este arquivo pode ser o `deployment_runs.py`

2020-11-17 12:18 UTC, fberanizo commented on pipelines/api/deployments.py
> +    """Handles GET requests to "/<deployment_id>/runs/logs."""
@shiguemi32 esta API não informa `run_id`, né (e sempre pega o mais recente).
Acho que pra ficar num padrão, poderia ser `runs/latests/logs` também.

2020-11-17 12:18 UTC, fberanizo commented on pipelines/controllers/experiments.py
>  created_at_desc = 'created_at desc'
@shiguemi32 este arquivo também pode ser renomeado para `experiment_runs.py` (e quando as coisas do projects estiverem aqui a gente cria outro `experiment_runs.py`.

2020-11-17 12:18 UTC, fberanizo commented on pipelines/controllers/runs.py
> -"""Runs controller."""
@shiguemi32 este arquivo também pode ser renomeado de `controllers/runs.py` para `controllers/deployment_runs.py``

2020-11-17 12:18 UTC, fberanizo commented on pipelines/controllers/project_deployments.py
> -"""Deployment controller."""
@shiguemi32 acho que pode ser `deployments.py` mesmo. 

Para organizar, talvez possa existir um outro arquivo que interage com o seldon/KFP e que este arquivo chama funções.

2020-11-17 12:18 UTC, fberanizo commented on pipelines/controllers/experiments.py
>          experiment_runs = client.list_runs(
Essa API de history não pode ser a mesma do `experiments/{experimentId}/runs` ? Qual  a diferença entre elas?

2020-11-17 12:18 UTC, fberanizo commented on docs/swagger.yaml
>    - name: "Deployments"
@shiguemi32 não comentei nada aqui no swagger, mas tem mudanças devido aos outros comentários.

2020-11-17 12:27 UTC, shiguemi32 commented on pipelines/controllers/experiments.py
>          experiment_runs = client.list_runs(
O experiments/{experimentId}/runs retorna o detalhe do ultimo pipeline rodado enquanto o history retorna todos os pipelines rodados por este experimentId

2020-11-17 12:35 UTC, fberanizo commented on pipelines/controllers/experiments.py
>          experiment_runs = client.list_runs(
Hmmm. Então acho que podemos usar aquele esquema de `runs/latest` aqui também.

2020-11-18 11:59 UTC, fberanizo requested changes

2020-11-18 11:59 UTC, fberanizo commented on pipelines/api/experiment_runs.py
> +    """Handles PUT requests to /."""
@shiguemi32 agora que a URL termina com `/runs` (o tranining_id não é mais passado como última parte da URL) o método mais adequado é o POST. O PUT é adequada quando for `runs/:runId`

2020-11-18 11:59 UTC, fberanizo commented on pipelines/api/experiment_runs.py
> +    return jsonify(get_experiment_run(experiment_id))
@shiguemi32 por favor deixe `run_id`  no lugar do latest.
Talvez no futuro a gente precise consultar as runs passadas. Por enquanto, retorne HTTP 400 para as consultas em que o run_id não é `latest`

2020-11-18 11:59 UTC, fberanizo commented on pipelines/api/experiment_runs.py
> +@bp.route("latest/retry", methods=["PUT"])
@shiguemi32 aqui também, troque o `latest` por `run_id`, por favor.

2020-11-18 11:59 UTC, fberanizo commented on pipelines/api/main.py
> +                       url_prefix=f"{PROJECT_ID_URL}/deployments")
@shiguemi32 está um pouco estranho `projects_blueprint` e o `url_prefix` terminar com `/deployments`. 
Talvez possa ser um `deployments_blueprint` e o import ser `from pipelines.api.deployments import bp as deployments_blueprint
`

2020-11-18 12:25 UTC, fberanizo commented
@shiguemi32 algumas considerações sobre o swagger:
- A Tag projects está fazendo muito sentido. Os paths podem ser movidos para deployments.
![image](https://user-images.githubusercontent.com/1791381/99530188-be95b600-297f-11eb-8e5c-a1f36e802604.png)

2020-11-20 15:25 UTC, fberanizo approved these changes

2020-11-20 15:25 UTC, merged